### ISSUE TITLE
The cache file location has moved!

### ISSUE THREAD

**Issue by anymy** [TehShrike/obsidian-tag-pages#1]
Obsidian Release v0.8.7 changes:
The cache file that was previously in vault/.obsidian/cache is now moved to the “APPDATA” folder under APPDATA\Obsidian\ObsidianCache\VAULT-ID.json. 

https://forum.obsidian.md/t/obsidian-release-v0-8-7/4774

I solved the problem for me by making a symbolic link named cache on the old location to the new file

**Comment by TehShrike** [comment]
Yeah, I've been needing to fix this, but haven't got the time yet – if someone wants to open a PR, the easiest way to get the appdata folder would probably be
- copy how application paths are being generated in https://github.com/sindresorhus/env-paths/blob/master/index.js
- figure out some way to derive the vault id from the vault directory (not sure how to do this...)

**Comment by TehShrike** [comment]
I asked in Discord, we'll see if a dev can provide a solution

**Comment by TehShrike** [comment]
No answers in Discord ¯\_(ツ)_/¯ I asked here https://forum.obsidian.md/t/is-there-any-way-to-derive-the-vault-id-from-the-vault-directory/5573

**Comment by TehShrike** [comment]
Fixed in 2.0.0.
